apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  selector:
    matchLabels: 
      app: conversao
  template:
    metadata: 
      labels:
        app: conversao
    spec:
      containers:
        - name: conversao
          image: christiannd/conversaotemperatura:v1
          ports: 
          - containerPort: 8080 
---
apiVersion: v1
kind: Deployment
metadata:
  name: service-conversao
spec:
  selector:
    app: conversao
  ports: 
    - port: 80
      targetPort: 8080
      nodePort: 30000
    type: NodePort
